language: python
python:
- 2.7.6
branches:
  only:
  - master
install:
- pip install -r requirements.txt
- sudo apt-get install -y asciidoc
script:
- make publish github
env:
  global:
    secure: f+nIBasRfR9Y0nyoWI8krzF1Cm3JosbOw4V420hmB4wDEDAFfNbJNq8eqM2rylgYTOUunz1/+sC9MMJKxQaE4S4egH1wkkH3jAGMHVKcS08GK83KUxpYxPrFe2/1/rWsiAK+4GUmBl9iLI3+gABJeeRIwgwnFkeZHl9Ww3i6fjs=
after_success:
- bash deploy.sh
